'use strict';
const $=selector=>document.querySelector(selector),labels={funny:'総合的な面白さ',promptFit:'お題適合',clarity:'明瞭さ',brevity:'簡潔さ',novelty:'新鮮さ',surprise:'意外性',twist:'ずらし',specificity:'具体性',escalation:'展開',rhythm:'言葉の着地',visualGrounding:'写真接続',instant:'瞬発性',edge:'切れ味'};
const storageKey='bokeHumanRatingV1';let dataset=null,index=0,ratings={};
const safeLoad=()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{return{}}};
const safeSave=value=>{try{localStorage.setItem(storageKey,JSON.stringify(value))}catch{}};
function buildScales(){const host=$('#scales');host.replaceChildren(...Object.entries(labels).map(([key,label])=>{const row=document.createElement('div');row.className='scale';row.dataset.key=key;const title=document.createElement('span');title.textContent=label;row.append(title,...[1,2,3,4,5].map(value=>{const button=document.createElement('button');button.type='button';button.textContent=value;button.addEventListener('click',()=>{ratings[dataset.items[index].id]??={};ratings[dataset.items[index].id][key]=value;paintScales()});return button}));return row}))}
function paintScales(){const current=ratings[dataset.items[index].id]||{};document.querySelectorAll('.scale').forEach(row=>[...row.querySelectorAll('button')].forEach(button=>button.classList.toggle('selected',Number(button.textContent)===current[row.dataset.key])))}
function render(){const item=dataset.items[index];$('#visualDescription').textContent=`写真の状況：${item.visualDescription}`;$('#prompt').textContent=item.prompt;$('#answer').textContent=item.answer;$('#progress').textContent=`${index+1} / ${dataset.items.length}`;$('#prevBtn').disabled=index===0;$('#nextBtn').textContent=index===dataset.items.length-1?'完了してダウンロード':'保存して次へ';paintScales()}
function exportRatings(){const raterId=$('#raterId').value.trim(),rows=Object.entries(ratings).map(([itemId,value])=>({itemId,...value}));const blob=new Blob([JSON.stringify({schemaVersion:1,raterId,createdAt:new Date().toISOString(),ratings:rows},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`boke-ratings-${raterId||'anonymous'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function start(){const raterId=$('#raterId').value.trim();if(!/^[0-9A-Za-z_-]{2,24}$/.test(raterId)){alert('評価者IDは半角英数字・ハイフン・下線で2〜24文字にしてください');return}const saved=safeLoad();ratings=saved.raterId===raterId&&saved.ratings?saved.ratings:{};dataset=await fetch('./research/validation-set.json',{credentials:'same-origin'}).then(response=>{if(!response.ok)throw new Error('load failed');return response.json()});$('#setup').hidden=true;$('#rating').hidden=false;buildScales();render()}
$('#startBtn').addEventListener('click',()=>start().catch(()=>alert('評価セットを読み込めませんでした')));$('#prevBtn').addEventListener('click',()=>{if(index){index--;render()}});$('#nextBtn').addEventListener('click',()=>{const id=dataset.items[index].id,current=ratings[id]||{};if(Object.keys(current).length!==Object.keys(labels).length){alert('すべての項目を1〜5で評価してください');return}safeSave({raterId:$('#raterId').value.trim(),ratings});if(index<dataset.items.length-1){index++;render()}else exportRatings()});$('#exportBtn').addEventListener('click',exportRatings);
